/**
 * Centralized React Query key factory.
 * Every key used by useQuery/useMutation/useQueryClient is defined here
 * so that cache invalidation is consistent and typo-free.
 */

export const queryKeys = {
  products: {
    all: ["products"] as const,
    lists: () => [...queryKeys.products.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.products.lists(), params] as const,
    details: () => [...queryKeys.products.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.products.details(), id] as const,
    demand: (id: string, params?: Record<string, unknown>) => [...queryKeys.products.detail(id), "demand", params] as const,
    demandHistory: (id: string, params?: Record<string, unknown>) => [...queryKeys.products.detail(id), "demand", "history", params] as const,
    demandProvenance: (id: string) => [...queryKeys.products.detail(id), "demand", "provenance"] as const,
    signals: (id: string, params?: Record<string, unknown>) => [...queryKeys.products.detail(id), "signals", params] as const,
    signalsSummary: (id: string) => [...queryKeys.products.detail(id), "signals", "summary"] as const,
    trends: (id: string) => [...queryKeys.products.detail(id), "trends"] as const,
  },

  demand: {
    all: ["demand"] as const,
    lists: () => [...queryKeys.demand.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.demand.lists(), params] as const,
  },

  signals: {
    all: ["signals"] as const,
    lists: () => [...queryKeys.signals.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.signals.lists(), params] as const,
    details: () => [...queryKeys.signals.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.signals.details(), id] as const,
  },

  evidence: {
    all: ["evidence"] as const,
    lists: () => [...queryKeys.evidence.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.evidence.lists(), params] as const,
    details: () => [...queryKeys.evidence.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.evidence.details(), id] as const,
    graph: (entityType: string, entityId: string) => [...queryKeys.evidence.all, "graph", entityType, entityId] as const,
    conflicts: (params?: Record<string, unknown>) => [...queryKeys.evidence.all, "conflicts", params] as const,
    conflictDetail: (id: string) => [...queryKeys.evidence.all, "conflicts", id] as const,
  },

  claims: {
    all: ["claims"] as const,
    lists: () => [...queryKeys.claims.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.claims.lists(), params] as const,
    details: () => [...queryKeys.claims.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.claims.details(), id] as const,
  },

  provenance: {
    get: (entityType: string, entityId: string) => ["provenance", entityType, entityId] as const,
  },

  supplyChain: {
    all: ["supplyChain"] as const,
    lists: () => [...queryKeys.supplyChain.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.supplyChain.lists(), params] as const,
    details: () => [...queryKeys.supplyChain.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.supplyChain.details(), id] as const,
    nodes: (id: string) => [...queryKeys.supplyChain.detail(id), "nodes"] as const,
    edges: (id: string) => [...queryKeys.supplyChain.detail(id), "edges"] as const,
    paths: (id: string) => [...queryKeys.supplyChain.detail(id), "paths"] as const,
    evidence: (id: string) => [...queryKeys.supplyChain.detail(id), "evidence"] as const,
    conflicts: (id: string) => [...queryKeys.supplyChain.detail(id), "conflicts"] as const,
    provenance: (id: string) => [...queryKeys.supplyChain.detail(id), "provenance"] as const,
    history: (id: string) => [...queryKeys.supplyChain.detail(id), "history"] as const,
    verifications: (id: string) => [...queryKeys.supplyChain.detail(id), "verifications"] as const,
    anomalies: (id: string) => [...queryKeys.supplyChain.detail(id), "anomalies"] as const,
    relationships: (params?: Record<string, unknown>) => [...queryKeys.supplyChain.all, "relationships", params] as const,
    claims: () => [...queryKeys.supplyChain.all, "claims"] as const,
    edgeDetail: (id: string) => [...queryKeys.supplyChain.all, "edges", id] as const,
    edgeProvenance: (id: string) => [...queryKeys.supplyChain.all, "edges", id, "provenance"] as const,
    edgeObservations: (id: string) => [...queryKeys.supplyChain.all, "edges", id, "observations"] as const,
  },

  logistics: {
    all: ["logistics"] as const,
    lists: () => [...queryKeys.logistics.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.logistics.lists(), params] as const,
    details: () => [...queryKeys.logistics.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.logistics.details(), id] as const,
    routes: (params?: Record<string, unknown>) => [...queryKeys.logistics.all, "routes", params] as const,
    legs: (params?: Record<string, unknown>) => [...queryKeys.logistics.all, "legs", params] as const,
    relationships: () => [...queryKeys.logistics.all, "relationships"] as const,
    nodes: (id: string) => [...queryKeys.logistics.detail(id), "nodes"] as const,
    assessmentLegs: (id: string) => [...queryKeys.logistics.detail(id), "legs"] as const,
    assessmentRoutes: (id: string) => [...queryKeys.logistics.detail(id), "routes"] as const,
    evidence: (id: string) => [...queryKeys.logistics.detail(id), "evidence"] as const,
    conflicts: (id: string) => [...queryKeys.logistics.detail(id), "conflicts"] as const,
    provenance: (id: string) => [...queryKeys.logistics.detail(id), "provenance"] as const,
    history: (id: string) => [...queryKeys.logistics.detail(id), "history"] as const,
    risks: (id: string) => [...queryKeys.logistics.detail(id), "risks"] as const,
    verifications: (id: string) => [...queryKeys.logistics.detail(id), "verifications"] as const,
    anomalies: (id: string) => [...queryKeys.logistics.detail(id), "anomalies"] as const,
  },

  pricing: {
    all: ["pricing"] as const,
    lists: () => [...queryKeys.pricing.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.pricing.lists(), params] as const,
    details: () => [...queryKeys.pricing.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.pricing.details(), id] as const,
    landedCosts: (params?: Record<string, unknown>) => [...queryKeys.pricing.all, "landedCosts", params] as const,
    landedCostDetail: (lcId: string) => [...queryKeys.pricing.all, "landedCosts", lcId] as const,
    scenarios: (params?: Record<string, unknown>) => [...queryKeys.pricing.all, "scenarios", params] as const,
    marketSnapshots: (params?: Record<string, unknown>) => [...queryKeys.pricing.all, "marketSnapshots", params] as const,
    assessmentLandedCosts: (id: string) => [...queryKeys.pricing.detail(id), "landedCosts"] as const,
    assessmentScenarios: (id: string) => [...queryKeys.pricing.detail(id), "scenarios"] as const,
    assessmentMarketSnapshots: (id: string) => [...queryKeys.pricing.detail(id), "marketSnapshots"] as const,
    assessmentRisks: (id: string) => [...queryKeys.pricing.detail(id), "risks"] as const,
    assessmentProvenance: (id: string) => [...queryKeys.pricing.detail(id), "provenance"] as const,
    assessmentHistory: (id: string) => [...queryKeys.pricing.detail(id), "history"] as const,
    observations: (params?: Record<string, unknown>) => [...queryKeys.pricing.all, "observations", params] as const,
    costComponents: () => [...queryKeys.pricing.all, "costComponents"] as const,
  },

  opportunity: {
    all: ["opportunity"] as const,
    assessments: (params?: Record<string, unknown>) => [...queryKeys.opportunity.all, "assessments", params] as const,
    assessmentDetail: (id: string) => [...queryKeys.opportunity.all, "assessments", id] as const,
    assessmentSignals: (id: string) => [...queryKeys.opportunity.assessmentDetail(id), "signals"] as const,
    assessmentRisks: (id: string) => [...queryKeys.opportunity.assessmentDetail(id), "risks"] as const,
    assessmentHistory: (id: string) => [...queryKeys.opportunity.assessmentDetail(id), "history"] as const,
    signals: (productId: string) => [...queryKeys.opportunity.all, "signals", productId] as const,
    risks: (productId: string) => [...queryKeys.opportunity.all, "risks", productId] as const,
    competitors: (productId: string) => [...queryKeys.opportunity.all, "competitors", productId] as const,
    competitorSnapshots: (productId: string) => [...queryKeys.opportunity.all, "competitorSnapshots", productId] as const,
  },

  sourcing: {
    all: ["sourcing"] as const,
    assessments: (params?: Record<string, unknown>) => [...queryKeys.sourcing.all, "assessments", params] as const,
    assessmentDetail: (id: string) => [...queryKeys.sourcing.all, "assessments", id] as const,
    assessmentHistory: (id: string) => [...queryKeys.sourcing.assessmentDetail(id), "history"] as const,
    productSuppliers: (productId: string) => [...queryKeys.sourcing.all, "products", productId, "suppliers"] as const,
    supplierDetail: (productId: string, supplierId: string) => [...queryKeys.sourcing.productSuppliers(productId), supplierId] as const,
    comparison: (productId: string) => [...queryKeys.sourcing.all, "products", productId, "comparison"] as const,
    viability: (productId: string) => [...queryKeys.sourcing.all, "products", productId, "viability"] as const,
    constraints: (productId: string) => [...queryKeys.sourcing.all, "products", productId, "constraints"] as const,
    supplierContacts: (supplierId: string) => [...queryKeys.sourcing.all, "suppliers", supplierId, "contacts"] as const,
  },

  research: {
    all: ["research"] as const,
    lists: () => [...queryKeys.research.all, "requests"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.research.lists(), params] as const,
    details: () => [...queryKeys.research.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.research.details(), id] as const,
    result: (id: string) => [...queryKeys.research.detail(id), "result"] as const,
    evidence: (id: string) => [...queryKeys.research.detail(id), "evidence"] as const,
    gaps: (id: string) => [...queryKeys.research.detail(id), "gaps"] as const,
    contradictions: (id: string) => [...queryKeys.research.detail(id), "contradictions"] as const,
    hypotheses: (id: string) => [...queryKeys.research.detail(id), "hypotheses"] as const,
    history: (params?: Record<string, unknown>) => [...queryKeys.research.all, "history", params] as const,
  },

  outreach: {
    all: ["outreach"] as const,
    campaigns: (params?: Record<string, unknown>) => [...queryKeys.outreach.all, "campaigns", params] as const,
    campaignDetail: (id: string) => [...queryKeys.outreach.all, "campaigns", id] as const,
    campaignOutreachs: (id: string) => [...queryKeys.outreach.campaignDetail(id), "outreachs"] as const,
    outreachs: (params?: Record<string, unknown>) => [...queryKeys.outreach.all, "outreachs", params] as const,
    outreachDetail: (id: string) => [...queryKeys.outreach.all, "outreachs", id] as const,
    thread: (id: string) => [...queryKeys.outreach.outreachDetail(id), "thread"] as const,
    qualification: (id: string) => [...queryKeys.outreach.outreachDetail(id), "qualification"] as const,
    outreachEvidence: (id: string) => [...queryKeys.outreach.outreachDetail(id), "evidence"] as const,
    followups: (id: string) => [...queryKeys.outreach.outreachDetail(id), "followups"] as const,
    templates: () => [...queryKeys.outreach.all, "templates"] as const,
  },

  calculations: {
    all: ["calculations"] as const,
    lists: () => [...queryKeys.calculations.all, "list"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.calculations.lists(), params] as const,
    details: () => [...queryKeys.calculations.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.calculations.details(), id] as const,
    provenance: (id: string) => [...queryKeys.calculations.detail(id), "provenance"] as const,
  },
} as const;
